@startuml

title Comparateur de vol

left to right direction

actor customer
actor airline
package checkout {
  customer -- (Check availability)
  (Other available flights) .> (Check availability) : extends
  (Book ticket) -- airline
  (Check availability) .> (Book ticket) : include
  (Other available flights) .> (Book ticket) : include
}


@enduml